/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.lib.framework.editor.wave.panel;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.prefs.Preferences;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import org.xbup.lib.framework.gui.options.api.OptionsPanel;
import org.xbup.lib.framework.gui.options.api.OptionsPanel.ModifiedOptionListener;
import org.xbup.lib.framework.gui.options.api.OptionsPanel.PathItem;
import org.xbup.lib.framework.gui.utils.ActionUtils;

/**
 * Wave editor color selection panel.
 *
 * @version 0.2.0 2016/01/29
 * @author XBUP Project (http://xbup.org)
 */
public class WaveColorPanel extends javax.swing.JPanel implements OptionsPanel {

    public static final String PREFERENCES_WAVE_COLOR_WAVE = "waveColor.wave";
    public static final String PREFERENCES_WAVE_COLOR_WAVE_FILL = "waveColor.waveFill";
    public static final String PREFERENCES_WAVE_COLOR_BACKGROUND = "waveColor.background";
    public static final String PREFERENCES_WAVE_COLOR_SELECTION = "waveColor.selection";
    public static final String PREFERENCES_WAVE_COLOR_CURSOR = "waveColor.cursor";
    public static final String PREFERENCES_WAVE_COLOR_CURSOR_WAVE = "waveColor.cursorWave";

    private ModifiedOptionListener modifiedOptionListener;
    private WaveColorPanelApi panelColorApi;
    private ResourceBundle resourceBundle;

    public WaveColorPanel(WaveColorPanelApi panelColorApi) {
        this.panelColorApi = panelColorApi;
        resourceBundle = ActionUtils.getResourceBundleByClass(WaveColorPanel.class);
        initComponents();
    }

    public Color getWaveColor() {
        return waveColorPanel.getBackground();
    }

    public Color getWaveFillColor() {
        return waveFillColorPanel.getBackground();
    }

    public Color getWaveBackgroundColor() {
        return waveBackgroundColorPanel.getBackground();
    }

    public Color getWaveSelectionColor() {
        return waveSelectionColorPanel.getBackground();
    }

    public Color getWaveCursorColor() {
        return waveCursorColorPanel.getBackground();
    }

    public Color getWaveCursorWaveColor() {
        return waveCursorWaveColorPanel.getBackground();
    }

    public void setDefaultAudioPanelColors() {
        setWaveColorsFromArray(panelColorApi.getDefaultWaveColors());
    }

    public void setWaveColor(Color color) {
        waveColorPanel.setBackground(color);
    }

    public void setWaveFillColor(Color color) {
        waveFillColorPanel.setBackground(color);
    }

    public void setWaveBackgroundColor(Color color) {
        waveBackgroundColorPanel.setBackground(color);
    }

    public void setWaveSelectionColor(Color color) {
        waveSelectionColorPanel.setBackground(color);
    }

    public void setWaveCursorColor(Color color) {
        waveCursorColorPanel.setBackground(color);
    }

    public void setWaveCursorWaveColor(Color color) {
        waveCursorWaveColorPanel.setBackground(color);
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        waveColorButton.setEnabled(enabled);
        waveBackgroundColorButton.setEnabled(enabled);
        waveSelectionColorButton.setEnabled(enabled);
        waveCursorColorButton.setEnabled(enabled);
        fillCurrentButton.setEnabled(enabled);
        fillDefaultButton.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        waveSelectionColorButton = new javax.swing.JButton();
        waveColorLabel = new javax.swing.JLabel();
        waveColorPanel = new javax.swing.JPanel();
        waveColorButton = new javax.swing.JButton();
        waveSelectionColorLabel = new javax.swing.JLabel();
        waveBackgroundColorLabel = new javax.swing.JLabel();
        waveCursorColorLabel = new javax.swing.JLabel();
        fillDefaultButton = new javax.swing.JButton();
        fillCurrentButton = new javax.swing.JButton();
        waveCursorColorPanel = new javax.swing.JPanel();
        waveCursorColorButton = new javax.swing.JButton();
        waveSelectionColorPanel = new javax.swing.JPanel();
        waveBackgroundColorPanel = new javax.swing.JPanel();
        waveBackgroundColorButton = new javax.swing.JButton();
        waveFillColorLabel = new javax.swing.JLabel();
        waveFillColorPanel = new javax.swing.JPanel();
        waveFillColorButton = new javax.swing.JButton();
        waveCursorWaveColorLabel = new javax.swing.JLabel();
        waveCursorWaveColorPanel = new javax.swing.JPanel();
        waveCursorWaveColorButton = new javax.swing.JButton();

        jColorChooser1.setName("jColorChooser1"); // NOI18N

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/xbup/lib/framework/editor/wave/panel/resources/WaveColorPanel"); // NOI18N
        waveSelectionColorButton.setText(bundle.getString("WaveColorPanel.selectButton.text")); // NOI18N
        waveSelectionColorButton.setName("waveSelectionColorButton"); // NOI18N
        waveSelectionColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveSelectionColorButtonActionPerformed(evt);
            }
        });

        waveColorLabel.setText(bundle.getString("WaveColorPanel.waveColorLabel.text")); // NOI18N
        waveColorLabel.setName("waveColorLabel"); // NOI18N

        waveColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        waveColorPanel.setName("waveColorPanel"); // NOI18N

        javax.swing.GroupLayout waveColorPanelLayout = new javax.swing.GroupLayout(waveColorPanel);
        waveColorPanel.setLayout(waveColorPanelLayout);
        waveColorPanelLayout.setHorizontalGroup(
            waveColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waveColorPanelLayout.setVerticalGroup(
            waveColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        waveColorButton.setText(bundle.getString("WaveColorPanel.selectButton.text")); // NOI18N
        waveColorButton.setName("waveColorButton"); // NOI18N
        waveColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveColorButtonActionPerformed(evt);
            }
        });

        waveSelectionColorLabel.setText(bundle.getString("WaveColorPanel.waveSelectionColorLabel.text")); // NOI18N
        waveSelectionColorLabel.setName("waveSelectionColorLabel"); // NOI18N

        waveBackgroundColorLabel.setText(bundle.getString("WaveColorPanel.waveBackgroundColorLabel.text")); // NOI18N
        waveBackgroundColorLabel.setName("waveBackgroundColorLabel"); // NOI18N

        waveCursorColorLabel.setText(bundle.getString("WaveColorPanel.waveCursorColorLabel.text")); // NOI18N
        waveCursorColorLabel.setName("waveCursorColorLabel"); // NOI18N

        fillDefaultButton.setText(bundle.getString("WaveColorPanel.fillDefaultButton.text")); // NOI18N
        fillDefaultButton.setName("fillDefaultButton"); // NOI18N
        fillDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillDefaultButtonActionPerformed(evt);
            }
        });

        fillCurrentButton.setText(bundle.getString("WaveColorPanel.fillCurrentButton.text")); // NOI18N
        fillCurrentButton.setName("fillCurrentButton"); // NOI18N
        fillCurrentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillCurrentButtonActionPerformed(evt);
            }
        });

        waveCursorColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        waveCursorColorPanel.setName("waveCursorColorPanel"); // NOI18N

        javax.swing.GroupLayout waveCursorColorPanelLayout = new javax.swing.GroupLayout(waveCursorColorPanel);
        waveCursorColorPanel.setLayout(waveCursorColorPanelLayout);
        waveCursorColorPanelLayout.setHorizontalGroup(
            waveCursorColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waveCursorColorPanelLayout.setVerticalGroup(
            waveCursorColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        waveCursorColorButton.setText(bundle.getString("WaveColorPanel.selectButton.text")); // NOI18N
        waveCursorColorButton.setName("waveCursorColorButton"); // NOI18N
        waveCursorColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveCursorColorButtonActionPerformed(evt);
            }
        });

        waveSelectionColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        waveSelectionColorPanel.setName("waveSelectionColorPanel"); // NOI18N

        javax.swing.GroupLayout waveSelectionColorPanelLayout = new javax.swing.GroupLayout(waveSelectionColorPanel);
        waveSelectionColorPanel.setLayout(waveSelectionColorPanelLayout);
        waveSelectionColorPanelLayout.setHorizontalGroup(
            waveSelectionColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waveSelectionColorPanelLayout.setVerticalGroup(
            waveSelectionColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        waveBackgroundColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        waveBackgroundColorPanel.setName("waveBackgroundColorPanel"); // NOI18N

        javax.swing.GroupLayout waveBackgroundColorPanelLayout = new javax.swing.GroupLayout(waveBackgroundColorPanel);
        waveBackgroundColorPanel.setLayout(waveBackgroundColorPanelLayout);
        waveBackgroundColorPanelLayout.setHorizontalGroup(
            waveBackgroundColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waveBackgroundColorPanelLayout.setVerticalGroup(
            waveBackgroundColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        waveBackgroundColorButton.setText(bundle.getString("WaveColorPanel.selectButton.text")); // NOI18N
        waveBackgroundColorButton.setName("waveBackgroundColorButton"); // NOI18N
        waveBackgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveBackgroundColorButtonActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("org/xbup/lib/framework/editor/wave/panel/Bundle"); // NOI18N
        waveFillColorLabel.setText(bundle1.getString("WaveColorPanel.waveFillColorLabel.text")); // NOI18N
        waveFillColorLabel.setName("waveFillColorLabel"); // NOI18N

        waveFillColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        waveFillColorPanel.setName("waveFillColorPanel"); // NOI18N

        javax.swing.GroupLayout waveFillColorPanelLayout = new javax.swing.GroupLayout(waveFillColorPanel);
        waveFillColorPanel.setLayout(waveFillColorPanelLayout);
        waveFillColorPanelLayout.setHorizontalGroup(
            waveFillColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waveFillColorPanelLayout.setVerticalGroup(
            waveFillColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        waveFillColorButton.setText(bundle1.getString("WaveColorPanel.waveFillColorButton.text")); // NOI18N
        waveFillColorButton.setName("waveFillColorButton"); // NOI18N
        waveFillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveFillColorButtonActionPerformed(evt);
            }
        });

        waveCursorWaveColorLabel.setText(bundle1.getString("WaveColorPanel.waveCursorWaveColorLabel.text")); // NOI18N
        waveCursorWaveColorLabel.setName("waveCursorWaveColorLabel"); // NOI18N

        waveCursorWaveColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        waveCursorWaveColorPanel.setName("waveCursorWaveColorPanel"); // NOI18N

        javax.swing.GroupLayout waveCursorWaveColorPanelLayout = new javax.swing.GroupLayout(waveCursorWaveColorPanel);
        waveCursorWaveColorPanel.setLayout(waveCursorWaveColorPanelLayout);
        waveCursorWaveColorPanelLayout.setHorizontalGroup(
            waveCursorWaveColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waveCursorWaveColorPanelLayout.setVerticalGroup(
            waveCursorWaveColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        waveCursorWaveColorButton.setText(bundle1.getString("WaveColorPanel.waveCursorWaveColorButton.text")); // NOI18N
        waveCursorWaveColorButton.setName("waveCursorWaveColorButton"); // NOI18N
        waveCursorWaveColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveCursorWaveColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(waveColorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(waveFillColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(waveBackgroundColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(waveSelectionColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waveSelectionColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waveBackgroundColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waveFillColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waveColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waveColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waveFillColorLabel)
                            .addComponent(waveBackgroundColorLabel)
                            .addComponent(waveSelectionColorLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fillCurrentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fillDefaultButton))
                            .addComponent(waveCursorColorLabel)
                            .addComponent(waveCursorWaveColorLabel))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waveCursorWaveColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waveCursorColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waveCursorWaveColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waveCursorColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waveColorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waveColorButton)
                    .addComponent(waveColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waveFillColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waveFillColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(waveFillColorButton))
                .addGap(18, 18, 18)
                .addComponent(waveBackgroundColorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waveBackgroundColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waveBackgroundColorButton))
                .addGap(18, 18, 18)
                .addComponent(waveSelectionColorLabel)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(waveSelectionColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waveSelectionColorButton))
                .addGap(18, 18, 18)
                .addComponent(waveCursorColorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waveCursorColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waveCursorColorButton))
                .addGap(18, 18, 18)
                .addComponent(waveCursorWaveColorLabel)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(waveCursorWaveColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waveCursorWaveColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillCurrentButton)
                    .addComponent(fillDefaultButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void waveColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveColorButtonActionPerformed
        jColorChooser1.setColor(waveColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, resourceBundle.getString("JColorChooser.title"), true, jColorChooser1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setWaveColor(jColorChooser1.getColor());
                setModified(true);
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_waveColorButtonActionPerformed

    private void waveBackgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveBackgroundColorButtonActionPerformed
        jColorChooser1.setColor(waveBackgroundColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, resourceBundle.getString("JColorChooser.title"), true, jColorChooser1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setWaveBackgroundColor(jColorChooser1.getColor());
                setModified(true);
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_waveBackgroundColorButtonActionPerformed

    private void waveSelectionColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveSelectionColorButtonActionPerformed
        jColorChooser1.setColor(waveSelectionColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, resourceBundle.getString("JColorChooser.title"), true, jColorChooser1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setWaveSelectionColor(jColorChooser1.getColor());
                setModified(true);
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_waveSelectionColorButtonActionPerformed

    private void waveCursorColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveCursorColorButtonActionPerformed
        jColorChooser1.setColor(waveCursorColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, resourceBundle.getString("JColorChooser.title"), true, jColorChooser1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setWaveCursorColor(jColorChooser1.getColor());
                setModified(true);
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_waveCursorColorButtonActionPerformed

    private void fillCurrentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillCurrentButtonActionPerformed
        setWaveColorsFromArray(panelColorApi.getCurrentWaveColors());
    }//GEN-LAST:event_fillCurrentButtonActionPerformed

    private void fillDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillDefaultButtonActionPerformed
        setDefaultAudioPanelColors();
    }//GEN-LAST:event_fillDefaultButtonActionPerformed

    private void waveFillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveFillColorButtonActionPerformed
        jColorChooser1.setColor(waveFillColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, resourceBundle.getString("JColorChooser.title"), true, jColorChooser1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setWaveFillColor(jColorChooser1.getColor());
                setModified(true);
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_waveFillColorButtonActionPerformed

    private void waveCursorWaveColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveCursorWaveColorButtonActionPerformed
        jColorChooser1.setColor(waveCursorWaveColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, resourceBundle.getString("JColorChooser.title"), true, jColorChooser1, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setWaveCursorWaveColor(jColorChooser1.getColor());
                setModified(true);
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_waveCursorWaveColorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fillCurrentButton;
    private javax.swing.JButton fillDefaultButton;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JButton waveBackgroundColorButton;
    private javax.swing.JLabel waveBackgroundColorLabel;
    private javax.swing.JPanel waveBackgroundColorPanel;
    private javax.swing.JButton waveColorButton;
    private javax.swing.JLabel waveColorLabel;
    private javax.swing.JPanel waveColorPanel;
    private javax.swing.JButton waveCursorColorButton;
    private javax.swing.JLabel waveCursorColorLabel;
    private javax.swing.JPanel waveCursorColorPanel;
    private javax.swing.JButton waveCursorWaveColorButton;
    private javax.swing.JLabel waveCursorWaveColorLabel;
    private javax.swing.JPanel waveCursorWaveColorPanel;
    private javax.swing.JButton waveFillColorButton;
    private javax.swing.JLabel waveFillColorLabel;
    private javax.swing.JPanel waveFillColorPanel;
    private javax.swing.JButton waveSelectionColorButton;
    private javax.swing.JLabel waveSelectionColorLabel;
    private javax.swing.JPanel waveSelectionColorPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<OptionsPanel.PathItem> getPath() {
        ArrayList<OptionsPanel.PathItem> path = new ArrayList<OptionsPanel.PathItem>();
        path.add(new PathItem("apperance", ""));
        path.add(new PathItem("colors", resourceBundle.getString("options.Path.0")));
        return path;
    }

    @Override
    public void loadFromPreferences(Preferences preferences) {
        Integer rgb;
        try {
            rgb = Integer.valueOf(preferences.get(PREFERENCES_WAVE_COLOR_WAVE, null));
            if (rgb != null) {
                setWaveColor(new Color(rgb));
            }
        } catch (NumberFormatException e) {
        }
        try {
            rgb = Integer.valueOf(preferences.get(PREFERENCES_WAVE_COLOR_BACKGROUND, null));
            if (rgb != null) {
                setWaveBackgroundColor(new Color(rgb));
            }
        } catch (NumberFormatException e) {
        }
        try {
            rgb = Integer.valueOf(preferences.get(PREFERENCES_WAVE_COLOR_SELECTION, null));
            if (rgb != null) {
                setWaveSelectionColor(new Color(rgb));
            }
        } catch (NumberFormatException e) {
        }
        try {
            rgb = Integer.valueOf(preferences.get(PREFERENCES_WAVE_COLOR_CURSOR, null));
            if (rgb != null) {
                setWaveCursorColor(new Color(rgb));
            }
        } catch (NumberFormatException e) {
        }
    }

    @Override
    public void saveToPreferences(Preferences preferences) {
        preferences.put(PREFERENCES_WAVE_COLOR_WAVE, Integer.toString(getWaveColor().getRGB()));
        preferences.put(PREFERENCES_WAVE_COLOR_WAVE_FILL, Integer.toString(getWaveFillColor().getRGB()));
        preferences.put(PREFERENCES_WAVE_COLOR_BACKGROUND, Integer.toString(getWaveBackgroundColor().getRGB()));
        preferences.put(PREFERENCES_WAVE_COLOR_SELECTION, Integer.toString(getWaveSelectionColor().getRGB()));
        preferences.put(PREFERENCES_WAVE_COLOR_CURSOR, Integer.toString(getWaveCursorColor().getRGB()));
        preferences.put(PREFERENCES_WAVE_COLOR_CURSOR_WAVE, Integer.toString(getWaveCursorWaveColor().getRGB()));
    }

    @Override
    public void applyPreferencesChanges() {
        panelColorApi.setCurrentWaveColors(panelColorApi.getDefaultWaveColors());
    }

    public void setWaveColorsFromArray(Color[] colors) {
        setWaveColor(colors[0]);
        setWaveFillColor(colors[1]);
        setWaveCursorColor(colors[2]);
        setWaveCursorWaveColor(colors[3]);
        setWaveBackgroundColor(colors[4]);
        setWaveSelectionColor(colors[5]);
    }

    public Color[] getWaveColorsAsArray() {
        Color[] colors = new Color[6];
        colors[0] = getWaveColor();
        colors[1] = getWaveFillColor();
        colors[2] = getWaveCursorColor();
        colors[3] = getWaveCursorWaveColor();
        colors[4] = getWaveBackgroundColor();
        colors[5] = getWaveSelectionColor();
        return colors;
    }

    private void setModified(boolean modified) {
        if (modifiedOptionListener != null) {
            modifiedOptionListener.wasModified();
        }
    }

    @Override
    public void setModifiedOptionListener(ModifiedOptionListener listener) {
        modifiedOptionListener = listener;
    }
}
