/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.gui.data.dialog;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import org.exbin.framework.XBBaseApplication;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.gui.component.GuiComponentModule;
import org.exbin.framework.gui.data.panel.DefinitionEditorPanel;
import org.exbin.framework.gui.menu.GuiMenuModule;
import org.exbin.xbup.core.catalog.XBACatalog;
import org.exbin.framework.gui.menu.api.MenuManagement;
import org.exbin.framework.gui.undo.GuiUndoModule;
import org.exbin.framework.gui.utils.ActionUtils;
import org.exbin.framework.gui.utils.TestApplication;
import org.exbin.framework.gui.utils.WindowUtils;

/**
 * XBManager catalog item editation dialog.
 *
 * @version 0.2.0 2016/03/23
 * @author ExBin Project (http://exbin.org)
 */
public class EditDefinitionDialog extends javax.swing.JDialog {

    private int dialogOption = JOptionPane.CLOSED_OPTION;

    private XBACatalog catalog;

    private DefinitionEditorPanel definitionEditorPanel;
    private MenuManagement menuManagement;
    private final java.util.ResourceBundle bundle = ActionUtils.getResourceBundleByClass(EditDefinitionDialog.class);
    private final XBApplication application;

    public EditDefinitionDialog(java.awt.Frame frame, boolean modal, XBApplication application) {
        super(frame, modal);
        this.application = application;
        initComponents();

        init();
    }

    private void init() {
        definitionEditorPanel = new DefinitionEditorPanel(application);
        add(definitionEditorPanel, BorderLayout.CENTER);

        WindowUtils.initWindow(this);
        WindowUtils.addHeaderPanel(this, bundle.getString("header.title"), bundle.getString("header.description"), bundle.getString("header.icon"));
        initComponent(this);
    }

    private void initComponent(Container container) {
        WindowUtils.assignGlobalKeyListener(container, setButton, cancelButton);
    }

    public int getDialogOption() {
        return dialogOption;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/exbin/framework/gui/data/dialog/resources/EditDefinitionDialog"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N

        controlPanel.setName("controlPanel"); // NOI18N

        cancelButton.setText(bundle.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        setButton.setText(bundle.getString("setButton.text")); // NOI18N
        setButton.setName("setButton"); // NOI18N
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addComponent(setButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(setButton))
                .addContainerGap())
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(657, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        dialogOption = JOptionPane.OK_OPTION;
        WindowUtils.closeWindow(this);
}//GEN-LAST:event_setButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dialogOption = JOptionPane.CANCEL_OPTION;
        WindowUtils.closeWindow(this);
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        TestApplication testApplication = WindowUtils.getDefaultAppEditor();
        testApplication.addModule(GuiUndoModule.MODULE_ID, new GuiUndoModule());
        testApplication.addModule(GuiMenuModule.MODULE_ID, new GuiMenuModule());
        testApplication.addModule(GuiComponentModule.MODULE_ID, new GuiComponentModule());
        WindowUtils.invokeWindow(new EditDefinitionDialog(new javax.swing.JFrame(), true, testApplication));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton setButton;
    // End of variables declaration//GEN-END:variables

    public void setMenuManagement(MenuManagement menuManagement) {
        this.menuManagement = menuManagement;
    }

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
        if (definitionEditorPanel != null) {
            definitionEditorPanel.setCatalog(catalog);
        }
    }
}
