/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.xbdoc_editor.dialog;

import hexedit.HexEditPanel;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import org.xbup.lib.core.block.XBTEditableDocument;
import org.xbup.tool.editor.base.api.XBEditorFrame;

/**
 * Dialog for document properties showing various information about file.
 *
 * @version 0.1.24 2014/10/20
 * @author XBUP Project (http://xbup.org)
 */
public class PropertiesDialog extends javax.swing.JDialog {

    private XBTEditableDocument doc;
    private final HexEditPanel hexPanel;

    public PropertiesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (parent instanceof XBEditorFrame) {
            setIconImage(((XBEditorFrame) parent).getMainFrameManagement().getFrameIcon());
        }

        hexPanel = new HexEditPanel((JFrame) parent);
        hexEditScrollPane.setViewportView(hexPanel);
        assignGlobalKeyListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        propertiesTabbedPane = new javax.swing.JTabbedPane();
        generalPropertiesPanel = new javax.swing.JPanel();
        fileNameLabel = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        fileSizeLabel = new javax.swing.JLabel();
        fileSizeTextField = new javax.swing.JTextField();
        fileTypeLabel = new javax.swing.JLabel();
        fileTypeTextField = new javax.swing.JTextField();
        extendedAreaPanel = new javax.swing.JPanel();
        hexEditScrollPane = new javax.swing.JScrollPane();
        loadFromButton3 = new javax.swing.JButton();
        saveFromButton = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/xbup/tool/xbeditor/module/xbdoceditor/dialog/resources/PropertiesDialog"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setLocationByPlatform(true);

        okButton.setText(bundle.getString("okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        fileNameLabel.setText(bundle.getString("jLabel1.text")); // NOI18N

        fileNameTextField.setEditable(false);

        fileSizeLabel.setText(bundle.getString("jLabel2.text")); // NOI18N

        fileSizeTextField.setEditable(false);

        fileTypeLabel.setText(bundle.getString("jLabel3.text")); // NOI18N

        fileTypeTextField.setEditable(false);

        javax.swing.GroupLayout generalPropertiesPanelLayout = new javax.swing.GroupLayout(generalPropertiesPanel);
        generalPropertiesPanel.setLayout(generalPropertiesPanelLayout);
        generalPropertiesPanelLayout.setHorizontalGroup(
            generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPropertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPropertiesPanelLayout.createSequentialGroup()
                        .addGroup(generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameLabel)
                            .addComponent(fileSizeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fileNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(fileSizeTextField)))
                    .addGroup(generalPropertiesPanelLayout.createSequentialGroup()
                        .addComponent(fileTypeLabel)
                        .addGap(66, 66, 66)
                        .addComponent(fileTypeTextField)))
                .addContainerGap())
        );
        generalPropertiesPanelLayout.setVerticalGroup(
            generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPropertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameLabel)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileTypeLabel)
                    .addComponent(fileTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        propertiesTabbedPane.addTab(bundle.getString("jPanel1.TabConstraints.tabTitle"), generalPropertiesPanel); // NOI18N

        loadFromButton3.setText(bundle.getString("jButton3.text")); // NOI18N
        loadFromButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFromButton3ActionPerformed(evt);
            }
        });

        saveFromButton.setText(bundle.getString("jButton2.text")); // NOI18N
        saveFromButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFromButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout extendedAreaPanelLayout = new javax.swing.GroupLayout(extendedAreaPanel);
        extendedAreaPanel.setLayout(extendedAreaPanelLayout);
        extendedAreaPanelLayout.setHorizontalGroup(
            extendedAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extendedAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extendedAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hexEditScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(extendedAreaPanelLayout.createSequentialGroup()
                        .addComponent(loadFromButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveFromButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        extendedAreaPanelLayout.setVerticalGroup(
            extendedAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extendedAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hexEditScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(extendedAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveFromButton)
                    .addComponent(loadFromButton3))
                .addContainerGap())
        );

        propertiesTabbedPane.addTab(bundle.getString("jPanel2.TabConstraints.tabTitle"), extendedAreaPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
            .addComponent(propertiesTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(propertiesTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO: Horrible extraction of data from HexEditPanel
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        try {
            HexEditPanel.saveToStream(buffer);
        } catch (IOException ex) {
            Logger.getLogger(PropertiesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        doc.setExtendedArea(new ByteArrayInputStream(buffer.toByteArray()));
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void loadFromButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFromButton3ActionPerformed
        HexEditPanel.openFile(null);
        hexPanel.repaint();
    }//GEN-LAST:event_loadFromButton3ActionPerformed

    private void saveFromButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFromButtonActionPerformed
        HexEditPanel.saveFile();
    }//GEN-LAST:event_saveFromButtonActionPerformed

    /**
     * Assign ESCAPE/ENTER key for all focusable components recursively.
     */
    private void assignGlobalKeyListener() {
        assignGlobalKeyListener(this);
    }

    private void assignGlobalKeyListener(Container comp) {
        Component[] comps = comp.getComponents();
        for (Component item : comps) {
            if (item.isFocusable()) {
                item.addKeyListener(new KeyListener() {
                    @Override
                    public void keyTyped(KeyEvent e) {
                    }

                    @Override
                    public void keyPressed(KeyEvent evt) {
                        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
                            okButton.doClick();
                        }
                        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                            if (evt.getSource() instanceof JButton) {
                                ((JButton) evt.getSource()).doClick();
                            } else {
                                okButton.doClick();
                            }
                        }
                    }

                    @Override
                    public void keyReleased(KeyEvent e) {
                    }
                });
            }

            if (item instanceof Container) {
                assignGlobalKeyListener((Container) item);
            }
        }
    }

    public void runDialog(XBTEditableDocument doc, String fileName) {
        this.doc = doc;
        fileNameTextField.setText(fileName);
        fileSizeTextField.setText(Long.toString(doc.getDocumentSize()));

        if (doc.getExtendedAreaSize() > 0) {
            HexEditPanel.loadFromStream(doc.getExtendedArea(), doc.getExtendedAreaSize());
        }

        setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ItemPropertiesDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extendedAreaPanel;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JLabel fileSizeLabel;
    private javax.swing.JTextField fileSizeTextField;
    private javax.swing.JLabel fileTypeLabel;
    private javax.swing.JTextField fileTypeTextField;
    private javax.swing.JPanel generalPropertiesPanel;
    private javax.swing.JScrollPane hexEditScrollPane;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loadFromButton3;
    private javax.swing.JButton okButton;
    private javax.swing.JTabbedPane propertiesTabbedPane;
    private javax.swing.JButton saveFromButton;
    // End of variables declaration//GEN-END:variables

}
