/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.lib.framework.editor.xbup.panel;

import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import org.xbup.lib.framework.client.api.ConnectionStatus;
import org.xbup.lib.framework.gui.utils.ActionUtils;

/**
 * Status panel for XB document editor.
 *
 * @version 0.2.0 2016/02/13
 * @author XBUP Project (http://xbup.org)
 */
public class XBDocStatusPanel extends javax.swing.JPanel {

    private ResourceBundle resourceBundle = ActionUtils.getResourceBundleByClass(XBDocStatusPanel.class);

    public XBDocStatusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectionStatusPanel = new javax.swing.JPanel();
        connectionStatusLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        connectionStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xbup/lib/framework/editor/xbup/resources/images/status/network-offline.png"))); // NOI18N

        javax.swing.GroupLayout connectionStatusPanelLayout = new javax.swing.GroupLayout(connectionStatusPanel);
        connectionStatusPanel.setLayout(connectionStatusPanelLayout);
        connectionStatusPanelLayout.setHorizontalGroup(
            connectionStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(connectionStatusLabel)
        );
        connectionStatusPanelLayout.setVerticalGroup(
            connectionStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(connectionStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        add(connectionStatusPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectionStatusLabel;
    private javax.swing.JPanel connectionStatusPanel;
    // End of variables declaration//GEN-END:variables

    public void setConnectionStatus(ConnectionStatus status) {
        connectionStatusLabel.setIcon(new ImageIcon(getClass().getResource(resourceBundle.getString("connectionStatus" + status.name() + ".icon"))));
        connectionStatusLabel.setToolTipText(resourceBundle.getString("connectionStatus" + status.name() + ".toolTipText"));
    }
}
