/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.service_manager.panel;

import java.awt.Component;
import java.awt.event.ActionEvent;
import org.xbup.lib.core.catalog.XBACatalog;
import org.xbup.tool.editor.module.service_manager.catalog.panel.CatalogFilesTreePanel;
import org.xbup.tool.editor.module.service_manager.catalog.panel.CatalogItemsTreePanel;
import org.xbup.tool.editor.module.service_manager.catalog.panel.CatalogStatusPanel;
import org.xbup.tool.editor.base.api.ActivePanelActionHandling;
import org.xbup.tool.editor.base.api.MainFrameManagement;
import org.xbup.tool.editor.base.api.MenuManagement;

/**
 * Simple Browser for catalog data
 *
 * @version 0.1 wr23.0 2013/09/26
 * @author XBUP Project (http://xbup.org)
 */
public class CatalogBrowserPanel extends javax.swing.JPanel implements ActivePanelActionHandling {

    private XBACatalog catalog;
    private CatalogItemsTreePanel catalogSpecificationsPanel;
    private CatalogFilesTreePanel catalogFilesPanel;
    private MenuManagement menuManagement;
    private MainFrameManagement mainFrameManagement;

    /** Creates new form CatalogBrowserPanel */
    public CatalogBrowserPanel() {
        initComponents();
        catalog = null;
        reloadCatalog();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("catalog");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    public XBACatalog getCatalog() {
        return catalog;
    }

    public void setCatalog(XBACatalog catalog) {
        if (catalog != null) {
            tabbedPane.removeAll();
        }
        this.catalog = catalog;
        reloadCatalog();
    }

    private void reloadCatalog() {
        if (catalog != null) {
            tabbedPane.add(new CatalogStatusPanel(catalog), "Catalog Status");
            catalogSpecificationsPanel = new CatalogItemsTreePanel(catalog);
            catalogSpecificationsPanel.setMainFrameManagement(mainFrameManagement);
            catalogFilesPanel = new CatalogFilesTreePanel(catalog);
            menuManagement.insertMainPopupMenu(catalogSpecificationsPanel.getPopupMenu(), 3);
            menuManagement.insertMainPopupMenu(catalogFilesPanel.getPopupMenu(), 5);
            tabbedPane.add(catalogSpecificationsPanel, "Specifications");
            tabbedPane.add(catalogFilesPanel, "Files");
        }
    }

    @Override
    public boolean updateActionStatus(Component component) {
        if (tabbedPane.getSelectedComponent() instanceof CatalogItemsTreePanel) {
            return catalogSpecificationsPanel.updateActionStatus(component);
        }

        return false;
    }

    @Override
    public void releaseActionStatus() {
        if (tabbedPane.getSelectedComponent() instanceof CatalogItemsTreePanel) {
            catalogSpecificationsPanel.releaseActionStatus();
        }
    }

    @Override
    public boolean performAction(String eventName, ActionEvent event) {
        if (tabbedPane.getSelectedComponent() instanceof CatalogItemsTreePanel) {
            return catalogSpecificationsPanel.performAction(eventName, event);
        }

        return false;
    }

    public void setMainFrameManagement(MainFrameManagement mainFrameManagement) {
        this.mainFrameManagement = mainFrameManagement;
    }

    public void setMenuManagement(MenuManagement menuManagement) {
        this.menuManagement = menuManagement;
    }
}
