/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.xbdoc_editor.panel;

import java.awt.Component;
import java.awt.Frame;
import javax.swing.SwingUtilities;
import org.xbup.lib.core.catalog.XBACatalog;
import org.xbup.lib.parser_tree.XBTTreeNode;
import org.xbup.tool.editor.module.xbdoc_editor.dialog.XBPropertyDialog;

/**
 * Properties panel custom renderer.
 *
 * @version 0.1.24 2014/11/10
 * @author XBUP Project (http://xbup.org)
 */
public class XBPropertyTableCellPanel extends javax.swing.JPanel {

    private int paramIndex;
    private XBACatalog catalog;
    private XBTTreeNode node;

    public XBPropertyTableCellPanel(XBACatalog catalog, XBTTreeNode node) {
        this.catalog = catalog;
        initComponents();
        this.node = node;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorButton = new javax.swing.JButton();
        valueTextField = new javax.swing.JTextField();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        editorButton.setText("..."); // NOI18N
        editorButton.setName("editorButton"); // NOI18N
        editorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButtonActionPerformed(evt);
            }
        });
        add(editorButton, java.awt.BorderLayout.EAST);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/xbup/tool/editor/module/xbdoc_editor/panel/resources/XBPropertyTableCellEditor"); // NOI18N
        valueTextField.setText(bundle.getString("jTextField1.text")); // NOI18N
        valueTextField.setName("valueTextField"); // NOI18N
        add(valueTextField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void editorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButtonActionPerformed
        XBPropertyDialog propertyDialog = new XBPropertyDialog(getFrame(), true);
        propertyDialog.setCatalog(catalog);
        propertyDialog.setLocationRelativeTo(propertyDialog.getParent());

        XBTTreeNode newNode = (XBTTreeNode) node.getParam(catalog, getParamIndex());
        propertyDialog.setRootBlock(newNode);
        propertyDialog.getDocumentPanel().reportStructureChange(newNode);
        propertyDialog.getDocumentPanel().updateItem();
        propertyDialog.setVisible(true);
    }//GEN-LAST:event_editorButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editorButton;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables

    public XBACatalog getCatalog() {
        return catalog;
    }

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
    }

    public XBTTreeNode getNode() {
        return node;
    }

    public void setNode(XBTTreeNode node) {
        this.node = node;
    }

    public int getParamIndex() {
        return paramIndex;
    }

    public void setParamIndex(int paramIndex) {
        this.paramIndex = paramIndex;
    }

    private Frame getFrame() {
        Component component = SwingUtilities.getWindowAncestor(this);
        while (!(component == null || component instanceof Frame)) {
            component = component.getParent();
        }
        return (Frame) component;
    }
}
