/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.xbdoc_editor.panel;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.xbup.lib.core.block.XBBlockDataMode;
import org.xbup.lib.core.block.XBBlockType;
import org.xbup.lib.core.block.declaration.XBBlockDecl;
import org.xbup.lib.core.block.declaration.XBContextBlockType;
import org.xbup.lib.core.catalog.XBACatalog;
import org.xbup.lib.core.catalog.base.XBCBlockSpec;
import org.xbup.lib.core.catalog.base.XBCRev;
import org.xbup.lib.core.catalog.base.XBCSpec;
import org.xbup.lib.core.catalog.base.XBCSpecDef;
import org.xbup.lib.core.catalog.base.XBCXDesc;
import org.xbup.lib.core.catalog.base.XBCXName;
import org.xbup.lib.core.catalog.base.service.XBCSpecService;
import org.xbup.lib.core.catalog.base.service.XBCXDescService;
import org.xbup.lib.core.catalog.base.service.XBCXNameService;
import org.xbup.lib.core.catalog.declaration.XBCBlockDecl;
import org.xbup.lib.parser_tree.XBTTreeNode;
import org.xbup.tool.editor.module.xbdoc_editor.dialog.ItemPropertiesDialog;

/**
 * Panel for properties of the actual panel.
 *
 * @version 0.1.22 2013/02/27
 * @author XBUP Project (http://xbup.org)
 */
public class XBPropertyPanel extends javax.swing.JPanel {

    private XBACatalog catalog;
    private Thread propertyThread;
    private Semaphore valueFillingSemaphore;
    private List<XBCBlockSpec> specList;
    private XBDocumentPanel activePanel;
    private XBPropertyTableCellRenderer cellRenderer;

    /** Creates new form XBPropertyPanel */
    public XBPropertyPanel(XBACatalog catalog) {
        this.catalog = catalog;

        initComponents();

//        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columns = jTable1.getColumnModel();
        columns.getColumn(0).setPreferredWidth(190);
        columns.getColumn(1).setPreferredWidth(190);
        columns.getColumn(0).setWidth(190);
        columns.getColumn(1).setWidth(190);
        cellRenderer = new XBPropertyTableCellRenderer(catalog);
        columns.getColumn(1).setCellRenderer(cellRenderer);
        columns.getColumn(1).setCellEditor(cellRenderer);
//        columns.getColumn(1).setModelIndex();

        propertyThread = null;
        valueFillingSemaphore = new Semaphore(1);
        specList = new ArrayList<XBCBlockSpec>();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertyPopupMenu = new javax.swing.JPopupMenu();
        popupItemOpenMenuItem = new javax.swing.JMenuItem();
        popupItemAddMenuItem = new javax.swing.JMenuItem();
        popupItemModifyMenuItem = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        popupUndoMenuItem = new javax.swing.JMenuItem();
        popupRedoMenuItem = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        popupCutMenuItem = new javax.swing.JMenuItem();
        popupCopyMenuItem = new javax.swing.JMenuItem();
        popupPasteMenuItem = new javax.swing.JMenuItem();
        popupDeleteMenuItem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        popupSelectAllMenuItem = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        popupItemPropertiesMenuItem = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        descTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();

        propertyPopupMenu.setName("propertyPopupMenu"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/xbup/tool/xbeditor/module/xbdoceditor/panel/resources/XBPropertyPanel"); // NOI18N
        popupItemOpenMenuItem.setText(bundle.getString("actionItemOpen.text")); // NOI18N
        popupItemOpenMenuItem.setName("popupItemOpenMenuItem"); // NOI18N
        propertyPopupMenu.add(popupItemOpenMenuItem);

        popupItemAddMenuItem.setText(bundle.getString("popupItemAddMenuItem.text")); // NOI18N
        popupItemAddMenuItem.setToolTipText(bundle.getString("popupItemAddMenuItem.toolTipText")); // NOI18N
        popupItemAddMenuItem.setName("popupItemAddMenuItem"); // NOI18N
        propertyPopupMenu.add(popupItemAddMenuItem);

        popupItemModifyMenuItem.setText(bundle.getString("popupItemModifyMenuItem.text")); // NOI18N
        popupItemModifyMenuItem.setToolTipText(bundle.getString("popupItemModifyMenuItem.toolTipText")); // NOI18N
        popupItemModifyMenuItem.setName("popupItemModifyMenuItem"); // NOI18N
        propertyPopupMenu.add(popupItemModifyMenuItem);

        jSeparator14.setName("jSeparator14"); // NOI18N
        propertyPopupMenu.add(jSeparator14);

        popupUndoMenuItem.setText(bundle.getString("popupUndoMenuItem.text")); // NOI18N
        popupUndoMenuItem.setToolTipText(bundle.getString("popupUndoMenuItem.toolTipText")); // NOI18N
        popupUndoMenuItem.setName("popupUndoMenuItem"); // NOI18N
        propertyPopupMenu.add(popupUndoMenuItem);

        popupRedoMenuItem.setText(bundle.getString("popupRedoMenuItem.text")); // NOI18N
        popupRedoMenuItem.setToolTipText(bundle.getString("popupRedoMenuItem.toolTipText")); // NOI18N
        popupRedoMenuItem.setName("popupRedoMenuItem"); // NOI18N
        propertyPopupMenu.add(popupRedoMenuItem);

        jSeparator10.setName("jSeparator10"); // NOI18N
        propertyPopupMenu.add(jSeparator10);

        popupCutMenuItem.setText("Cut"); // NOI18N
        popupCutMenuItem.setName("popupCutMenuItem"); // NOI18N
        propertyPopupMenu.add(popupCutMenuItem);

        popupCopyMenuItem.setText("Copy"); // NOI18N
        popupCopyMenuItem.setName("popupCopyMenuItem"); // NOI18N
        propertyPopupMenu.add(popupCopyMenuItem);

        popupPasteMenuItem.setText("Paste"); // NOI18N
        popupPasteMenuItem.setName("popupPasteMenuItem"); // NOI18N
        propertyPopupMenu.add(popupPasteMenuItem);

        popupDeleteMenuItem.setText("Delete"); // NOI18N
        popupDeleteMenuItem.setName("popupDeleteMenuItem"); // NOI18N
        propertyPopupMenu.add(popupDeleteMenuItem);

        jSeparator7.setName("jSeparator7"); // NOI18N
        propertyPopupMenu.add(jSeparator7);

        popupSelectAllMenuItem.setText("Select All"); // NOI18N
        popupSelectAllMenuItem.setName("popupSelectAllMenuItem"); // NOI18N
        propertyPopupMenu.add(popupSelectAllMenuItem);

        jSeparator16.setName("jSeparator16"); // NOI18N
        propertyPopupMenu.add(jSeparator16);

        popupItemPropertiesMenuItem.setText(bundle.getString("popupItemPropertiesMenuItem.text")); // NOI18N
        popupItemPropertiesMenuItem.setName("popupItemPropertiesMenuItem"); // NOI18N
        propertyPopupMenu.add(popupItemPropertiesMenuItem);

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(propertyPopupMenu);
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setName("jPanel1"); // NOI18N

        nameLabel.setText(bundle.getString("nameLabel.text")); // NOI18N

        descLabel.setText(bundle.getString("descLabel.text")); // NOI18N
        descLabel.setName("descLabel"); // NOI18N

        descTextField.setEditable(false);
        descTextField.setName("descTextField"); // NOI18N

        nameTextField.setEditable(false);
        nameTextField.setName("nameTextField"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JMenuItem popupCopyMenuItem;
    private javax.swing.JMenuItem popupCutMenuItem;
    private javax.swing.JMenuItem popupDeleteMenuItem;
    private javax.swing.JMenuItem popupItemAddMenuItem;
    private javax.swing.JMenuItem popupItemModifyMenuItem;
    private javax.swing.JMenuItem popupItemOpenMenuItem;
    private javax.swing.JMenuItem popupItemPropertiesMenuItem;
    private javax.swing.JMenuItem popupPasteMenuItem;
    private javax.swing.JMenuItem popupRedoMenuItem;
    private javax.swing.JMenuItem popupSelectAllMenuItem;
    private javax.swing.JMenuItem popupUndoMenuItem;
    private javax.swing.JPopupMenu propertyPopupMenu;
    // End of variables declaration//GEN-END:variables

    public void setActiveNode(XBTTreeNode node) {
        nameTextField.setText("");
        descTextField.setText("");
        cellRenderer.setNode(node);
        new PropertyThread(this, node).start();
    }

    /**
     * @return the catalog
     */
    public XBACatalog getCatalog() {
        return catalog;
    }

    /**
     * @param catalog the catalog to set
     */
    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
        cellRenderer.setCatalog(catalog);
    }

    /**
     * @return the propertyThread
     */
    private Thread getPropertyThread() {
        return propertyThread;
    }

    /**
     * @param propertyThread the propertyThread to set
     */
    private void setPropertyThread(Thread propertyThread) {
        this.propertyThread = propertyThread;
    }

    /**
     * @return the valueFillingSemaphore
     */
    private Semaphore getValueFillingSemaphore() {
        return valueFillingSemaphore;
    }

    private Frame getFrame() {
        return null;
    }

    // TODO: Prepare values and then fill it property panel
    private class PropertyThread extends Thread {

        private XBPropertyPanel propertyPanel;
        private XBTTreeNode node;
        private DefaultTableModel tableModel;

        public PropertyThread(XBPropertyPanel propertyPanel, XBTTreeNode node) {
            super();
            this.propertyPanel = propertyPanel;
            this.node = node;
        }

        @Override
        public void start() {
            super.start();
            try {
                getValueFillingSemaphore().acquire();
                tableModel = ((DefaultTableModel) jTable1.getModel());
                for (int i = tableModel.getRowCount()-1; i >= 0; i--) {
                    tableModel.removeRow(i);
                }
                specList.clear();
                propertyPanel.setPropertyThread(this);
                getValueFillingSemaphore().release();
                fillPanel();
            } catch (InterruptedException ex) {
                Logger.getLogger(XBPropertyPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (node != null) {
                nameTextField.setText(getCaption(node));
            }
        }

        public void fillPanel() {
            if ((catalog == null) || (node == null)) {
                return;
            }
            XBBlockType type = node.getBlockType();
            if (!(type instanceof XBContextBlockType)) {
                return;
            }
            XBBlockDecl decl = ((XBContextBlockType) type).getBlockDecl();
            if (propertyThread != this) {
                return;
            }
            XBCSpecService specService = (XBCSpecService) catalog.getCatalogService(XBCSpecService.class);
            if (decl instanceof XBCBlockDecl) {
                XBCXNameService nameService = (XBCXNameService) catalog.getCatalogService(XBCXNameService.class);
                XBCXDescService descService = (XBCXDescService) catalog.getCatalogService(XBCXDescService.class);
                XBCBlockSpec spec = ((XBCBlockDecl) decl).getBlockSpec(catalog);
                if (propertyThread != this) {
                    return;
                }
                if (spec != null) {
                    XBCXDesc desc = descService.getItemDesc(spec);
                    if (propertyThread != this) {
                        return;
                    }
                    long bindCount = specService.getSpecDefsCount(spec);
                    try {
                        getValueFillingSemaphore().acquire();
                        if (propertyPanel.getPropertyThread() == this) {
                            if (desc != null) {
                                descTextField.setText(desc.getText());
                            }
                            for (int i = 0; i < bindCount; i++) {
                                // TODO: Exclusive lock
                                XBCSpecDef bind = specService.getSpecDefByOrder(spec, i);
                                Object[] row = new Object[2];
                                if (bind != null) {
                                    XBCRev rowRev = bind.getTarget();
                                    XBCSpec rowSpec = rowRev.getParent();
                                    XBCXName rowName = nameService.getItemName(rowSpec);
                                    if (rowName != null) {
                                        row[0] = rowName.getText();
                                    }
                                }
                                row[1] = "";
                                tableModel.addRow(row);
                                specList.add(spec);
                            }
                        }
                        getValueFillingSemaphore().release();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(XBPropertyPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }

    private String getCaption(XBTTreeNode node) {
        if (node.getDataMode() == XBBlockDataMode.DATA_BLOCK) {
            return "Data Block";
        }
        XBBlockType blockType = node.getBlockType();
        if (blockType instanceof XBContextBlockType) {
            XBBlockDecl blockDecl = ((XBContextBlockType) blockType).getBlockDecl();
            if (blockDecl instanceof XBCBlockDecl) {
                XBCBlockSpec blockSpec = ((XBCBlockDecl) blockDecl).getBlockSpec(catalog);
                if (catalog != null) {
                    XBCXNameService nameService = (XBCXNameService) catalog.getCatalogService(XBCXNameService.class);
                    return nameService.getDefaultCaption(blockSpec);
                }
            }
        } else if (blockType instanceof XBContextBlockType) {
            XBCBlockDecl blockDecl = (XBCBlockDecl) ((XBContextBlockType) blockType).getBlockDecl();
            XBCBlockSpec blockSpec = blockDecl.getBlockSpec(catalog);
            if (catalog != null) {
                XBCXNameService nameService = (XBCXNameService) catalog.getCatalogService(XBCXNameService.class);
                return nameService.getDefaultCaption(blockSpec);
            }
        }

        if (blockType == null) {
            return "Unknown";
        }
        return "Unknown" + " (" + Integer.toString(blockType.getGroupID().getInt()) + ", "+ Integer.toString(blockType.getBlockID().getInt())+")";
    }

    public void actionItemProperties() {
        ItemPropertiesDialog dialog = new ItemPropertiesDialog(getFrame(),true);
        dialog.setCatalog(catalog);
        dialog.runDialog(activePanel.getSelectedItem());
    }

    public void actionItemOpen() {
    }

    public boolean isStub1Enabled() {
        return activePanel.getMode() == XBDocumentPanel.PanelMode.TEXT;
    }

    private boolean addEnabled = false;
    public boolean isAddEnabled() {
        return addEnabled;
    }

    public void setAddEnabled(boolean b) {
        boolean old = isAddEnabled();
        this.addEnabled = b;
        firePropertyChange("addEnabled", old, isAddEnabled());
    }

    private boolean undoAvailable = false;
    public boolean isUndoAvailable() {
        return undoAvailable;
    }

    public void setUndoAvailable(boolean b) {
        boolean old = isUndoAvailable();
        this.undoAvailable = b;
        firePropertyChange("undoAvailable", old, isUndoAvailable());
    }

    public boolean isRedoAvailable() {
        return false; //activePanel.canRedo();
    }

    public boolean isEditEnabled() {
        if (activePanel == null) {
            return false;
        }
        return activePanel.isEditEnabled() && (activePanel.getMode() == XBDocumentPanel.PanelMode.TREE);
    }

    public boolean isPasteEnabled() {
        if (activePanel == null) {
            return false;
        }
        return activePanel.isPasteEnabled();
    }

    public boolean isFalse() {
        return false;
    }
}
