/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.service_manager.catalog.panel;

import javax.swing.JList;
import org.xbup.lib.core.catalog.XBACatalog;
import org.xbup.lib.core.catalog.base.service.XBCItemService;
import org.xbup.lib.core.catalog.base.service.XBCNodeService;
import org.xbup.lib.core.catalog.base.service.XBCRevService;
import org.xbup.lib.core.catalog.base.service.XBCSpecService;

/**
 * Panel for catalog status.
 *
 * @version 0.1.24 2014/12/08
 * @author XBUP Project (http://xbup.org)
 */
public class CatalogStatusPanel extends javax.swing.JPanel {

    private XBACatalog catalog;
    private final CatalogExtensionsListModel extModel;

    public CatalogStatusPanel(XBACatalog catalog) {
        this.catalog = catalog;
        extModel = new CatalogExtensionsListModel();
        initComponents();

        updateCatalog();
        // Patch for unchecked call to setModel(ListModel<E>) as a member of the raw type JList
        JList newList = new JList();
        newList.setModel(extModel);
        extensionsList = newList;
        extensionsScrollPane.setViewportView(extensionsList);
    }

    public CatalogStatusPanel() {
        this(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogStatusPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        extensionsPanel = new javax.swing.JPanel();
        extensionsScrollPane = new javax.swing.JScrollPane();
        extensionsList = new javax.swing.JList();

        catalogStatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalog Status"));

        jPanel2.setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setText("Count of Items");
        jPanel2.add(jLabel1);

        jTextField1.setEditable(false);
        jTextField1.setText("unknown");
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1);

        jLabel2.setText("Nodes");
        jPanel2.add(jLabel2);

        jTextField2.setEditable(false);
        jTextField2.setText("unknown");
        jTextField2.setBorder(null);
        jPanel2.add(jTextField2);

        jLabel3.setText("Specifications");
        jPanel2.add(jLabel3);

        jTextField3.setEditable(false);
        jTextField3.setText("unknown");
        jTextField3.setBorder(null);
        jPanel2.add(jTextField3);

        jLabel5.setText("Formats");
        jPanel2.add(jLabel5);

        jTextField5.setEditable(false);
        jTextField5.setText("unknown");
        jTextField5.setBorder(null);
        jPanel2.add(jTextField5);

        jLabel6.setText("Groups");
        jPanel2.add(jLabel6);

        jTextField6.setEditable(false);
        jTextField6.setText("unknown");
        jTextField6.setBorder(null);
        jPanel2.add(jTextField6);

        jLabel7.setText("Blocks");
        jPanel2.add(jLabel7);

        jTextField7.setEditable(false);
        jTextField7.setText("unknown");
        jTextField7.setBorder(null);
        jPanel2.add(jTextField7);

        jLabel4.setText("Defs");
        jPanel2.add(jLabel4);

        jTextField4.setEditable(false);
        jTextField4.setText("unknown");
        jTextField4.setBorder(null);
        jPanel2.add(jTextField4);

        jLabel8.setText("Revisions");
        jPanel2.add(jLabel8);

        jTextField8.setEditable(false);
        jTextField8.setText("unknown");
        jTextField8.setBorder(null);
        jPanel2.add(jTextField8);

        javax.swing.GroupLayout catalogStatusPanelLayout = new javax.swing.GroupLayout(catalogStatusPanel);
        catalogStatusPanel.setLayout(catalogStatusPanelLayout);
        catalogStatusPanelLayout.setHorizontalGroup(
            catalogStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        catalogStatusPanelLayout.setVerticalGroup(
            catalogStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        extensionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Extensions"));

        extensionsScrollPane.setViewportView(extensionsList);

        javax.swing.GroupLayout extensionsPanelLayout = new javax.swing.GroupLayout(extensionsPanel);
        extensionsPanel.setLayout(extensionsPanelLayout);
        extensionsPanelLayout.setHorizontalGroup(
            extensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extensionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extensionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        extensionsPanelLayout.setVerticalGroup(
            extensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extensionsPanelLayout.createSequentialGroup()
                .addComponent(extensionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catalogStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(extensionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(catalogStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extensionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel catalogStatusPanel;
    private javax.swing.JList extensionsList;
    private javax.swing.JPanel extensionsPanel;
    private javax.swing.JScrollPane extensionsScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
        updateCatalog();
    }

    private void updateCatalog() {
        extModel.setCatalog(catalog);
        Long count = catalog == null ? null : ((XBCItemService) catalog.getCatalogService(XBCItemService.class)).getItemsCount();
        jTextField1.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCNodeService) catalog.getCatalogService(XBCNodeService.class)).getItemsCount();
        jTextField2.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCSpecService) catalog.getCatalogService(XBCSpecService.class)).getItemsCount();
        jTextField3.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCSpecService) catalog.getCatalogService(XBCSpecService.class)).getDefsCount();
        jTextField4.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCSpecService) catalog.getCatalogService(XBCSpecService.class)).getAllFormatSpecsCount();
        jTextField5.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCSpecService) catalog.getCatalogService(XBCSpecService.class)).getAllGroupSpecsCount();
        jTextField6.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCSpecService) catalog.getCatalogService(XBCSpecService.class)).getAllBlockSpecsCount();
        jTextField7.setText(count == null ? "unknown" : count.toString());
        count = catalog == null ? null : ((XBCRevService) catalog.getCatalogService(XBCRevService.class)).getItemsCount();
        jTextField8.setText(count == null ? "unknown" : count.toString());
    }
}
