/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.service_manager.catalog.panel;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.JTextComponent;
import org.xbup.lib.core.catalog.XBACatalog;
import org.xbup.lib.core.catalog.base.XBCBase;
import org.xbup.lib.core.catalog.base.XBCItem;
import org.xbup.lib.core.catalog.base.XBCXStri;
import org.xbup.lib.core.catalog.base.service.XBCItemService;
import org.xbup.lib.core.catalog.base.service.XBCXDescService;
import org.xbup.lib.core.catalog.base.service.XBCXNameService;
import org.xbup.lib.core.catalog.base.service.XBCXStriService;
import org.xbup.lib.catalog.entity.XBEItem;
import org.xbup.lib.catalog.entity.XBENode;
import org.xbup.lib.catalog.entity.XBEXFile;
import org.xbup.lib.catalog.entity.XBEXHDoc;
import org.xbup.lib.catalog.entity.XBEXLanguage;
import org.xbup.lib.catalog.entity.service.XBEXFileService;
import org.xbup.lib.catalog.entity.service.XBEXHDocService;
import org.xbup.lib.core.catalog.base.XBCXFile;
import org.xbup.lib.core.catalog.base.XBCXHDoc;
import org.xbup.lib.core.catalog.base.XBCXLanguage;
import org.xbup.lib.core.catalog.base.service.XBCXFileService;
import org.xbup.lib.core.catalog.base.service.XBCXHDocService;
import org.xbup.lib.core.catalog.base.service.XBCXLangService;
import sun.swing.DefaultLookup;

/**
 * Panel for properties of the catalog item.
 *
 * @version 0.1.24 2014/11/22
 * @author XBUP Project (http://xbup.org)
 */
public class CatalogItemEditPanel extends javax.swing.JPanel {

    private XBACatalog catalog;
    private XBCItem catalogItem;
    private CatalogPropetiesDocTableCellPanel cellPanel = null;

    public CatalogItemEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        propertiesTable = new JTable(null) {
            @Override
            public boolean editCellAt(int row, int column, EventObject e) {
                boolean result = super.editCellAt(row, column, e);
                final Component editor = getEditorComponent();
                if (editor == null || !(editor instanceof JTextComponent)) {
                    return result;
                }
                if (e instanceof MouseEvent) {
                    EventQueue.invokeLater(new Runnable() {

                        @Override
                        public void run() {
                            ((JTextComponent) editor).selectAll();
                        }

                    });
                } else {
                    ((JTextComponent) editor).selectAll();
                }
                return result;
            }
        };

        setLayout(new java.awt.BorderLayout());

        scrollPane.setName("scrollPane"); // NOI18N

        propertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        propertiesTable.setName("propertiesTable"); // NOI18N
        scrollPane.setViewportView(propertiesTable);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable propertiesTable;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public void setCatalogItem(XBCItem catalogItem) {
        this.catalogItem = catalogItem;
        DefaultTableModel tableModel = (DefaultTableModel) propertiesTable.getModel();

        XBCXStriService striService = (XBCXStriService) catalog.getCatalogService(XBCXStriService.class);
        XBCXNameService nameService = (XBCXNameService) catalog.getCatalogService(XBCXNameService.class);
        XBCXDescService descService = (XBCXDescService) catalog.getCatalogService(XBCXDescService.class);

        // Remove all rows
        for (int i = tableModel.getRowCount() - 1; i > 0; i--) {
            tableModel.removeRow(i);
        }

        String parentId = "";
        if (catalogItem.getParent() != null) {
            parentId = catalogItem.getParent().getId().toString();
        }
        tableModel.addRow(new String[]{"Name", nameService.getDefaultText(catalogItem)});
        tableModel.addRow(new String[]{"Description", descService.getDefaultText(catalogItem)});
        tableModel.addRow(new String[]{"ParentId", parentId});
        String itemIndex = null;
        Long xbIndex = catalogItem.getXBIndex();
        if (xbIndex != null) {
            itemIndex = xbIndex.toString();
        }
        tableModel.addRow(new String[]{"XBIndex", itemIndex});

        String pathName = null;
        XBCXStri stringId = striService.getItemStringId(catalogItem);
        if (stringId != null) {
            pathName = stringId.getText();
        }
        tableModel.addRow(new String[]{"StringId", pathName});
        tableModel.addRow(new String[]{"HDoc", ""});

        cellPanel = new CatalogPropetiesDocTableCellPanel(catalog);
        cellPanel.setCatalogItem(catalogItem);
        TableColumnModel columns = propertiesTable.getColumnModel();
        columns.getColumn(1).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                if (row == 5) {
                    cellPanel.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                    cellPanel.getCellComponent().setBorder(null);
                    return cellPanel;
                }

                return super.getTableCellRendererComponent(table, value,
                        isSelected, hasFocus, row, column);
            }
        });
        DefaultCellEditor defaultCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
                if (row == 5) {
                    cellPanel.setBackground(table.getSelectionBackground());
                    cellPanel.getCellComponent().setBorder(DefaultLookup.getBorder(cellPanel.getCellComponent(), ui, "Table.focusCellHighlightBorder"));
                    return cellPanel;
                }
                return super.getTableCellEditorComponent(table, value, isSelected, row, column);
            }
        };
        defaultCellEditor.setClickCountToStart(0);
        columns.getColumn(1).setCellEditor(defaultCellEditor);
        propertiesTable.repaint();
    }

    public XBCItem getCatalogItem() {
        return catalogItem;
    }

    public void persist() {
        if (propertiesTable.getCellEditor() != null) {
            propertiesTable.getCellEditor().stopCellEditing();
        }

        XBCXStriService striService = (XBCXStriService) catalog.getCatalogService(XBCXStriService.class);
        XBCItemService itemService = (XBCItemService) catalog.getCatalogService(XBCItemService.class);
        XBCXNameService nameService = (XBCXNameService) catalog.getCatalogService(XBCXNameService.class);
        XBCXDescService descService = (XBCXDescService) catalog.getCatalogService(XBCXDescService.class);

        DefaultTableModel tableModel = (DefaultTableModel) propertiesTable.getModel();
        nameService.setDefaultText(catalogItem, (String) tableModel.getValueAt(0, 1));
        descService.setDefaultText(catalogItem, (String) tableModel.getValueAt(1, 1));
        if (catalogItem instanceof XBEItem) {
            String xbIndex = (String) tableModel.getValueAt(3, 1);
            if (xbIndex != null) {
                ((XBEItem) catalogItem).setXBIndex(Long.parseLong(xbIndex));
            } else {
                ((XBEItem) catalogItem).setXBIndex(null);
            }

            String parentId = (String) tableModel.getValueAt(2, 1);
            if ((!"".equals(parentId)) && (parentId != null)) {
                ((XBEItem) catalogItem).setParent((XBEItem) itemService.getItem(Long.parseLong(parentId)));
            } else {
                ((XBEItem) catalogItem).setParent(null);
            }

            itemService.persistItem((XBCBase) catalogItem);
        }

        striService.setItemStringIdText(catalogItem, (String) tableModel.getValueAt(4, 1));
        
        String document = cellPanel.getDocument();
        if (document != null) {
            XBCXFileService fileService = (XBCXFileService)catalog.getCatalogService(XBCXFileService.class);
            XBCXHDocService hdocService = (XBCXHDocService) catalog.getCatalogService(XBCXHDocService.class);

            XBCXHDoc itemHDoc = hdocService.getDocumentation(catalogItem);
            
            if (document.isEmpty()) {
                if (itemHDoc != null) {
                    fileService.removeItem(itemHDoc.getDocFile());
                    hdocService.removeItem(itemHDoc);
                }
            } else {
                if (itemHDoc == null) {
                    XBCXLangService langService = (XBCXLangService) catalog.getCatalogService(XBCXLangService.class);
                    XBCXLanguage defaultLanguage = langService.getDefaultLang();
                    itemHDoc = new XBEXHDoc();
                    ((XBEXHDoc) itemHDoc).setLang((XBEXLanguage) defaultLanguage);
                    ((XBEXHDoc) itemHDoc).setItem((XBEItem) catalogItem);
                }
                
                XBCXFile itemHDocFile = itemHDoc.getDocFile();
                if (itemHDocFile == null) {
                    XBCXStri stringId = striService.getItemStringId(catalogItem);
                    String itemPath = stringId == null ? "" : stringId.getText();
                    itemHDocFile = (XBCXFile) fileService.createItem();
                    ((XBEXFile) itemHDocFile).setFilename("hdoc-" + itemPath);
                    ((XBEXFile) itemHDocFile).setNode((XBENode) catalogItem.getParent());
                    ((XBEXHDoc) itemHDoc).setDocFile((XBEXFile) itemHDocFile);
                }

                OutputStream fileOutputStream = ((XBEXFileService) fileService).setFile(itemHDocFile);
                OutputStreamWriter writer = new OutputStreamWriter(fileOutputStream);
                try {
                    writer.write(document);
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(CatalogItemEditPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
    
                ((XBEXFileService) fileService).persistItem((XBEXFile) itemHDocFile);
                ((XBEXHDocService) hdocService).persistItem((XBEXHDoc) itemHDoc);
            }
        }
    }

    public XBACatalog getCatalog() {
        return catalog;
    }

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
    }
}
