/*
 * Copyright (C) XBUP Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.xbup.tool.editor.module.service_manager.catalog.panel;

import java.awt.Component;
import java.awt.Frame;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.xbup.lib.core.catalog.XBACatalog;
import org.xbup.lib.core.catalog.base.XBCSpec;
import org.xbup.lib.core.catalog.base.service.XBCSpecService;

/**
 * XBManager Catalog Item Edit Documentation Panel.
 *
 * @version 0.1.24 2014/11/13
 * @author XBUP Project (http://xbup.org)
 */
public class CatalogRevsPanel extends javax.swing.JPanel {

    private XBACatalog catalog;
    private XBCSpec spec;
    private XBCSpecService specService;
    private final CatalogRevsTableModel revsModel;

    public CatalogRevsPanel(XBACatalog catalog) {
        revsModel = new CatalogRevsTableModel(catalog);
        initComponents();

        revisionsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                updateItemStatus();
            }
        });

        updateItemStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        revisionsScrollPane = new javax.swing.JScrollPane();
        revisionsTable = new javax.swing.JTable();
        revisionsControlPanel = new javax.swing.JPanel();
        addRevButton = new javax.swing.JButton();
        removeRevButton = new javax.swing.JButton();
        editRevButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/xbup/tool/editor/module/service_manager/catalog/panel/resources/CatalogItemEditDefinitionPanel"); // NOI18N
        setToolTipText(bundle.getString("toolTipText")); // NOI18N
        setLayout(new java.awt.BorderLayout());

        revisionsTable.setModel(revsModel);
        revisionsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        revisionsScrollPane.setViewportView(revisionsTable);

        add(revisionsScrollPane, java.awt.BorderLayout.CENTER);

        addRevButton.setText("Add");
        addRevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRevButtonActionPerformed(evt);
            }
        });

        removeRevButton.setText("Remove");
        removeRevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRevButtonActionPerformed(evt);
            }
        });

        editRevButton.setText("Edit...");

        javax.swing.GroupLayout revisionsControlPanelLayout = new javax.swing.GroupLayout(revisionsControlPanel);
        revisionsControlPanel.setLayout(revisionsControlPanelLayout);
        revisionsControlPanelLayout.setHorizontalGroup(
            revisionsControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revisionsControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRevButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editRevButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeRevButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        revisionsControlPanelLayout.setVerticalGroup(
            revisionsControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revisionsControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(revisionsControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRevButton)
                    .addComponent(removeRevButton)
                    .addComponent(editRevButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(revisionsControlPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void addRevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRevButtonActionPerformed

    }//GEN-LAST:event_addRevButtonActionPerformed

    private void removeRevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRevButtonActionPerformed
        int selectedRow = revisionsTable.getSelectedRow();

        // removeList.add(specDef);
        // revsModel.removeItem(specDef);
        updateItemStatus();
    }//GEN-LAST:event_removeRevButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRevButton;
    private javax.swing.JButton editRevButton;
    private javax.swing.JButton removeRevButton;
    private javax.swing.JPanel revisionsControlPanel;
    private javax.swing.JScrollPane revisionsScrollPane;
    private javax.swing.JTable revisionsTable;
    // End of variables declaration//GEN-END:variables

    private void updateItemStatus() {
        int selectedRow = revisionsTable.getSelectedRow();
        int rowsCount = revsModel.getRowCount();
        if ((selectedRow >= 0) && (selectedRow < rowsCount)) {
            editRevButton.setEnabled(true);
            removeRevButton.setEnabled(true);
        } else {
            editRevButton.setEnabled(false);
            removeRevButton.setEnabled(false);
        }
        revisionsTable.repaint();
    }

    public void setSpec(XBCSpec spec) {
        this.spec = spec;
        revsModel.setSpec(spec);
        updateItemStatus();
    }

    public XBCSpec getSpec() {
        return spec;
    }

    public XBACatalog getCatalog() {
        return catalog;
    }

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
        specService = (XBCSpecService) catalog.getCatalogService(XBCSpecService.class);
        revsModel.setCatalog(catalog);
        repaint();
    }

    private Frame getFrame() {
        Component component = SwingUtilities.getWindowAncestor(this);
        while (!(component == null || component instanceof Frame)) {
            component = component.getParent();
        }
        return (Frame) component;
    }
}
